application: haitwu
version: 1
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /m
  static_dir: static

- url: /.*
  script: main.py
  
